from dataclasses import dataclass
from typing import Callable, Protocol


@dataclass
class WrenchResult:
    result: str
    actual_torque: float
    actual_angle: float


class TorqueWrench(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def set_program(self, program_no: int) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def on_tightening_done(self, callback: Callable[[WrenchResult], None]) -> None: ...
